"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_status\
$haskell\
$python\
$character"""

[directory]
style = "bold #268bd2"
format = "[$path]($style) "
truncation_length = 2

[git_branch]
symbol = ""
style = "bold #6c71c4"
format = "[:: $branch]($style) "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "#586e75"
conflicted = "="
untracked = "?"
modified = "!"
staged = "+"
renamed = ">"
deleted = "x"
ahead = "^"
behind = "v"

[haskell]
symbol = "λ"
style = "bold #6c71c4"
format = '([$symbol $version]($style) )'

[python]
symbol = "py"
style = "#859900"
format = '([$symbol $virtualenv]($style) )'

[character]
success_symbol = "[λ>](bold #d33682)"
error_symbol = "[λ>](bold #dc322f)"

[cmd_duration]
disabled = true
