"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$haskell\
$python\
$character"""

[username]
style_user = "#FF91AF"
style_root = "bold #E06C75"
format = "[$user]($style) · "
show_always = true
aliases = { "luizgustavo" = "(*ˊᵕˋ*)" }

[hostname]
style = "#7F848E"
disabled = true
format = "[$hostname]($style) "
ssh_only = false
aliases = { "MacBook-Air" = "air" }

[directory]
style = "#61AFEF"
format = "[$path]($style) "
truncation_length = 3

[git_branch]
format = "[:: $branch]($style)"
style = "#7F848E"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "#7F848E"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](bold #D19A66) ($ahead_behind$stashed)]($style)"
style = "#56B6C2"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[cmd_duration]
format = "[$duration]($style) "
style = "#E5C07B"

[haskell]
symbol = "λ"
style = "#C678DD"
format = '([$symbol $version]($style) )'

[python]
format = "[$virtualenv]($style) "
style = "#7F848E"
detect_extensions = []
detect_files = []

[character]
success_symbol = "[λ](#ABB2BF)"
error_symbol = "[λ](#E06C75)"
vimcmd_symbol = "[λ](#98C379)"
